apiVersion: apps/v1
kind: Deployment
metadata:
  name: siyuan
  namespace: siyuan
  labels:
    app: siyuan
spec:
  replicas: 1
  selector:
    matchLabels:
      app: siyuan
  template:
    metadata:
      labels:
        app: siyuan
    spec:
      containers:
      - name: siyuan
        image: apkdv/siyuan-unlock:latest
        ports:
        - containerPort: 6806
        envFrom:
        - configMapRef:
            name: siyuan-config
        env:
        - name: ACCESSAUTHCODE
          valueFrom:
            secretKeyRef:
              name: siyuan-secret
              key: ACCESSAUTHCODE
              optional: true
        volumeMounts:
        - name: siyuan-data
          mountPath: /siyuan/workspace
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
      volumes:
      - name: siyuan-data
        persistentVolumeClaim:
          claimName: siyuan-data